# Generated by Django 5.2.1 on 2025-06-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date_of_meeting',
            new_name='date',
        ),
    ]
